//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Base_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int id_documento { get; set; }
        public int id_proyecto { get; set; }
        public string nombre { get; set; }
        public string tipoArchivo { get; set; }
        public string url { get; set; }
        public System.DateTime fechaSubida { get; set; }
    }
}
