//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Base_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public int id_proyecto { get; set; }
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_fin { get; set; }
        public string Estado { get; set; }
        public decimal Presupuesto { get; set; }
    }
}
